language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
 - 5.4
 - 5.5
 - 5.6
 - 7.0
 - 7.1

env:
  matrix:
      - DB=pgsql MOODLE_BRANCH=MOODLE_27_STABLE V2=false
      - DB=pgsql MOODLE_BRANCH=MOODLE_28_STABLE V2=false
      - DB=pgsql MOODLE_BRANCH=MOODLE_29_STABLE V2=false
      - DB=pgsql MOODLE_BRANCH=MOODLE_30_STABLE V2=false
      - DB=pgsql MOODLE_BRANCH=MOODLE_31_STABLE V2=false
      - DB=pgsql MOODLE_BRANCH=MOODLE_32_STABLE V2=true
      - DB=mysqli MOODLE_BRANCH=MOODLE_27_STABLE V2=false
      - DB=mysqli MOODLE_BRANCH=MOODLE_28_STABLE V2=false
      - DB=mysqli MOODLE_BRANCH=MOODLE_29_STABLE V2=false
      - DB=mysqli MOODLE_BRANCH=MOODLE_30_STABLE V2=false
      - DB=mysqli MOODLE_BRANCH=MOODLE_31_STABLE V2=false
      - DB=mysqli MOODLE_BRANCH=MOODLE_32_STABLE V2=true

matrix:
  exclude:
    - env: DB=pgsql MOODLE_BRANCH=MOODLE_27_STABLE
      php: 7.0
    - env: DB=pgsql MOODLE_BRANCH=MOODLE_28_STABLE
      php: 7.0
    - env: DB=pgsql MOODLE_BRANCH=MOODLE_29_STABLE
      php: 7.0
    - env: DB=mysqli MOODLE_BRANCH=MOODLE_27_STABLE
      php: 7.0
    - env: DB=mysqli MOODLE_BRANCH=MOODLE_28_STABLE
      php: 7.0
    - env: DB=mysqli MOODLE_BRANCH=MOODLE_29_STABLE
      php: 7.0
    - env: DB=pgsql MOODLE_BRANCH=MOODLE_27_STABLE
      php: 7.1
    - env: DB=pgsql MOODLE_BRANCH=MOODLE_28_STABLE
      php: 7.1
    - env: DB=pgsql MOODLE_BRANCH=MOODLE_29_STABLE
      php: 7.1
    - env: DB=mysqli MOODLE_BRANCH=MOODLE_27_STABLE
      php: 7.1
    - env: DB=mysqli MOODLE_BRANCH=MOODLE_28_STABLE
      php: 7.1
    - env: DB=mysqli MOODLE_BRANCH=MOODLE_29_STABLE
      php: 7.1
    - env: DB=mysqli MOODLE_BRANCH=MOODLE_32_STABLE
      php: 5.4
    - env: DB=mysqli MOODLE_BRANCH=MOODLE_32_STABLE
      php: 5.5
    - env: DB=pgsql MOODLE_BRANCH=MOODLE_32_STABLE
      php: 5.4
    - env: DB=pgsql MOODLE_BRANCH=MOODLE_32_STABLE
      php: 5.5
    - env: DB=mysqli MOODLE_BRANCH=MOODLE_33_STABLE
      php: 5.4
    - env: DB=mysqli MOODLE_BRANCH=MOODLE_33_STABLE
      php: 5.5
    - env: DB=pgsql MOODLE_BRANCH=MOODLE_33_STABLE
      php: 5.4
    - env: DB=pgsql MOODLE_BRANCH=MOODLE_33_STABLE
      php: 5.5

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 8.9
  - nvm use 8.9
  - cd ../..
  - composer selfupdate
  - if [ "$V2" = false ]; then composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^1; fi
  - if [ "$V2" = true ]; then composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^2; fi
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - if [ "$V2" = true ]; - moodle-plugin-ci savepoints; fi
  - if [ "$V2" = true ]; then moodle-plugin-ci mustache; fi
  - if [ "$V2" = true ]; then moodle-plugin-ci grunt; fi
  - if [ "$V2" = false ]; then moodle-plugin-ci csslint; fi
  - if [ "$V2" = false ]; then moodle-plugin-ci jshint; fi
  - moodle-plugin-ci shifter
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat